//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contacts
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class MyContactTbl
    {
        ContactEntities1 context = new ContactEntities1();
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Job_ID_FK { get; set; }
        public int City_ID_FK { get; set; }

        public virtual CityTbl CityTbl { get; set; }
        public virtual JobTbl JobTbl { get; set; }
        public string Image { get; set; }



        public void addContact(string name, string family, string email, string mobile, DateTime date, int city, int job, string image)
        {
            MyContactTbl mycontact = new MyContactTbl();
            try
            {
                mycontact.Name = name;
                mycontact.Family = family;
                mycontact.Email = email;
                mycontact.Mobile = mobile;
                mycontact.Birthday = date;
                mycontact.City_ID_FK = city;
                mycontact.Job_ID_FK = job;
                mycontact.Image = image;
                context.MyContactTbls.Add(mycontact);
                context.SaveChanges();
                MessageBox.Show("insert contact complated", "succsess", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception)
            {
                MessageBox.Show("insert contact feild", "error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            finally
            {
                mycontact = null;

            }

        }
    }
}
